# Generated by Django 3.2.9 on 2021-11-15 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.CharField(max_length=128, verbose_name='封面')),
                ('content', models.CharField(max_length=255, verbose_name='内容')),
                ('favor_count', models.PositiveIntegerField(default=0, verbose_name='赞数')),
                ('viewer_count', models.PositiveIntegerField(default=0, verbose_name='报名数')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='评论数')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=64, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=64, null=True, verbose_name='头像')),
                ('token', models.CharField(blank=True, max_length=64, null=True, verbose_name='用户Token')),
            ],
        ),
        migrations.CreateModel(
            name='NewsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viedo_path', models.CharField(max_length=255, verbose_name='视频路径')),
                ('imag_path', models.CharField(max_length=255, verbose_name='照片')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.news', verbose_name='动态')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='news', to='api.userinfo', verbose_name='发布者'),
        ),
        migrations.CreateModel(
            name='KcTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ks_time', models.DateTimeField(verbose_name='课程开始时间')),
                ('js_time', models.DateField(verbose_name='课程结束时间')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.newsdetail', verbose_name='发布者')),
            ],
        ),
    ]
