# Generated by Django 3.2.9 on 2021-11-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('last_time', models.DateTimeField(auto_now=True, help_text='上次登录时间', verbose_name='last_time')),
                ('token', models.CharField(help_text='uuid', max_length=36, verbose_name='token')),
                ('is_delete', models.BooleanField(help_text='是否删除', verbose_name='is_delete')),
                ('czy', models.CharField(help_text='操作人员', max_length=32, verbose_name='czy')),
                ('username', models.CharField(help_text='管理账号', max_length=32, verbose_name='username')),
                ('password', models.CharField(help_text='密码', max_length=32, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('last_time', models.DateTimeField(auto_now=True, help_text='上次登录时间', verbose_name='last_time')),
                ('token', models.CharField(help_text='uuid', max_length=36, verbose_name='token')),
                ('is_delete', models.BooleanField(help_text='是否删除', verbose_name='is_delete')),
                ('czy', models.CharField(help_text='操作人员', max_length=32, verbose_name='czy')),
                ('image_url', models.CharField(help_text='存放图片的url', max_length=255, verbose_name='image_url')),
                ('video_url', models.CharField(help_text='存放视频的url', max_length=255, verbose_name='video_url')),
                ('name', models.CharField(help_text='课程名称', max_length=36, verbose_name='name')),
                ('kcjj', models.TextField(help_text='课程简介', verbose_name='kcjj')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('last_time', models.DateTimeField(auto_now=True, help_text='上次登录时间', verbose_name='last_time')),
                ('token', models.CharField(help_text='uuid', max_length=36, verbose_name='token')),
                ('is_delete', models.BooleanField(help_text='是否删除', verbose_name='is_delete')),
                ('czy', models.CharField(help_text='操作人员', max_length=32, verbose_name='czy')),
                ('image_url', models.CharField(help_text='存放图片的url', max_length=36, verbose_name='image_url')),
                ('name', models.CharField(help_text='老师名字', max_length=16, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('last_time', models.DateTimeField(auto_now=True, help_text='上次登录时间', verbose_name='last_time')),
                ('token', models.CharField(help_text='uuid', max_length=36, verbose_name='token')),
                ('is_delete', models.BooleanField(help_text='是否删除', verbose_name='is_delete')),
                ('czy', models.CharField(help_text='操作人员', max_length=32, verbose_name='czy')),
                ('username', models.CharField(help_text='公司账号', max_length=32, verbose_name='username')),
                ('password', models.CharField(help_text='公司密码', max_length=32, verbose_name='password')),
                ('address', models.CharField(help_text='公司地址', max_length=32, verbose_name='address')),
            ],
        ),
    ]
