# Generated by Django 3.2.9 on 2021-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='emails',
            field=models.CharField(default='abc', help_text='电子邮箱', max_length=128, verbose_name='emails'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lsjj',
            field=models.TextField(default='abc', help_text='老师简介', verbose_name='lsjj'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default='abc', help_text='老师手机号', max_length=11, verbose_name='phone'),
        ),
    ]
