# Generated by Django 3.2.9 on 2021-12-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211209_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='emails',
            field=models.CharField(help_text='电子邮箱', max_length=128, verbose_name='emails'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='lsjj',
            field=models.TextField(help_text='老师简介', verbose_name='lsjj'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(help_text='老师手机号', max_length=11, verbose_name='phone'),
        ),
    ]
