# Generated by Django 3.2.9 on 2021-12-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211209_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image_url',
            field=models.CharField(help_text='存放图片的url', max_length=255, verbose_name='image_url'),
        ),
    ]
