# Generated by Django 3.2.9 on 2021-12-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211210_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_time',
            name='end_time',
            field=models.DateTimeField(help_text='课程结束时间', verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='course_time',
            name='start_time',
            field=models.DateTimeField(help_text='课程开始时间', verbose_name='start_time'),
        ),
        migrations.CreateModel(
            name='Course_choose',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='create_time')),
                ('last_time', models.DateTimeField(auto_now=True, help_text='上次登录时间', verbose_name='last_time')),
                ('token', models.CharField(help_text='uuid', max_length=36, verbose_name='token')),
                ('is_delete', models.BooleanField(help_text='是否删除', verbose_name='is_delete')),
                ('czy', models.CharField(help_text='操作人员', max_length=32, verbose_name='czy')),
                ('teacher', models.CharField(help_text='老师', max_length=32, verbose_name='teacher')),
                ('course_time', models.DateTimeField(help_text='课程开始时间', verbose_name='start_time')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
