# Generated by Django 3.2.9 on 2021-12-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211221_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_choose',
            name='course_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course_time'),
        ),
        migrations.AlterField(
            model_name='course_choose',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.teacher'),
        ),
    ]
